### ISSUE TITLE
Console Error on join

### ISSUE THREAD

**Issue by Chris6ix** [Sportkanone123/ClientDetector#19]
**General Information**
Server version: Paper 1.19 #81
Client version: Vanilla 1.19
Plugin version: 2.5.1

**Describe the bug**
When joining the server, this error appears in the console: https://pastebin.com/c8Cm9uez

**To Reproduce**
Join the Server?

**Comment by Sportkanone123** [comment]
Should be fixed with 1594f4bbe2406d9886c1677ceb6243ec45518a2c.

**Comment by Chris6ix** [comment]
Hey @Sportkanone123 is this commit included in the latest version on Spigot?
Because with the latest version from Spigot (2.5.2) I still get this console error when I join my 1.19.2 server.

![image](https://user-images.githubusercontent.com/65610536/185637565-da78b388-213f-410b-813f-d730ff15509a.png)

**Comment by Sportkanone123** [comment]
No, the latest version on SpigotMC does not contain these bug fixes. However I will release a new version today.

**Comment by Chris6ix** [comment]
Okay thanks :)

**Comment by Sportkanone123** [comment]
Sorry that it took so long, update is now on SpigotMC.
